### ISSUE TITLE
Implement JSON schema approach

### ISSUE THREAD

**Issue by EvanLovely** [bolt-design-system/bolt#302]
[JSON Schemas](https://spacetelescope.github.io/understanding-json-schema/) define data structure clearly, and this will allow the components to clearly state what data they need and how it should look. This will help prevent mysterious errors and confusing implementations while providing other tangable and exciting benefits, such as:

* Automatically generated documentation for all components.
* Providing tests when the components are used in Drupal to determine potential points of failure earlier and easier - helping to save time and ease frustration.
* Providing component creators with effecient methods of showcasing component variations.

This issue is for setting up the tooling & foundation and then implementing for handful of components referenced below; more issues will be made later for adding schema docs to other components.

This initial implementation should include JSON schemas for the following components / variations:

- [ ] [Buttons](https://github.com/bolt-design-system/bolt/issues/308) (including the primary button, secondary button, and text button sub-types, etc)
- [ ] [Headlines](https://github.com/bolt-design-system/bolt/issues/358) (including the text, headline, subheadline, and eyebrow sub-types, etc)
- [ ] [Blockquotes](https://github.com/bolt-design-system/bolt/issues/307)

**Comment by sghoweri** [comment]
@EvanLovely @remydenton I'm gonna need to throw a tiny little wrench into the original implementation we stubbed out in Portland 😉:

While I do agree with having the example Twig demos / variations live in the apps/pl folder, I do NOT think we should have the JSON schema definition live there: https://github.com/bolt-design-system/bolt/blob/epic/refactor/apps/pattern-lab--workshop/src/_patterns/02-components/bolt-button/src/button.schema.json

This needs to live with the source of truth (the component) and be part of the packe resources bundled together and published with Lerna.

That way other environments (PL, Drupal, React, whoever) could reference this Schema as a programmatic set of instructions documenting expected usage, config options, etc vs merely being an example living in Pattern Lab.

Yes, I realize that interoperable schema validation might take a little time to get to, however simply by having it all live in the same place is one step that'll get us there.

**Comment by EvanLovely** [comment]
> JSON Schema in component folder

Yep, agreed

**Comment by sghoweri** [comment]
@EvanLovely @remydenton PRs for 2 out of the 3 of these coming up today!
