### ISSUE TITLE
Refactor Build Tools

### ISSUE THREAD

**Issue by EvanLovely** [bolt-design-system/bolt#304]
The build tools need to be restructured in a way that allows the consumers of Bolt in other environments like Drupal to be able to compile just the components they want in the correct way with minimal knowledge of how it all comes together inside Bolt. 

- [ ] Decoupled build tools that can compile a specific collection of components in multiple environments
- [x] `clean` command
- [x] `watch` command
- [x] pattern lab commands
- [ ] lint commands
- [ ] test commands
- [ ] production toggle via `--prod` or `NODE_ENV=production`
- [x] Merge config in with default config and validate via schema
- [x] Ensure the current implementation support both a physical .css file output + importing CSS directly into a JS component (a must for our Web Components)?
- [x] Break commands out into `bolt build`, `bolt build --watch`, etc

**Comment by sghoweri** [comment]
@EvanLovely the current workflow / build tools also includes functionality relating to:

- [ ] image commands (ex. optimize images via imagemin + create responsive image cuts)
- [ ] pre-build svg icons
- [ ] deploy a local version of your code to Netlify to share

**Comment by EvanLovely** [comment]
Thanks for adding those; I think there needs to be a second set of tools for those that just create in Bolt. Basically sets of tools that consuming environments don't need; for example these tools aren't needed in a Drupal setup and so shouldn't have dependencies installed:

- deploy

probably more, but we can add later

**Comment by EvanLovely** [comment]
From @sghoweri right [here](https://github.com/bolt-design-system/bolt/pull/310#discussion_r160469828):

> How do I configure the public path that's critical for having Webpack know where to Ajax in code from?
