### ISSUE TITLE
Update components to compile using new build tools

### ISSUE THREAD

**Issue by EvanLovely** [bolt-design-system/bolt#309]
Each of the components in `packages/components/*` needs to be able to compile using the new build tools.

### What to do for each component

1. In `*.scss` remove any `@import` statement such as `@import "@bolt/settings-all"` and leaving just `@import "@bolt/core"`.
1. Ensure `package.json` has these keys that point at a **single** asset each (all are optional)
    - `style` key pointing to a scss file
    - `main` pointing towards a js files
    - `twig` pointing towards a twig file
1. In `package.json`, adjust any dependencies as you see fit 
    - this is were most troubleshooting happened for me 
    - Sometimes the package version was not exactly what is the repo, so Lerna won't symlink it for you
    - Sometimes the dependency isn't a package in 1.x, but was in 0.x - time to prune
    - Also we're cleaning up any `scripts` related to building the individual components; we do that in bundles now 
1. Add component name to top level package.json under `workspaces` 
1. Add component to Pattern Lab - so if it was the `@bolt/components-button` package and it's version was ~`0.5.1`~ `0.7.0-beta.5`, in the file `apps/pattern-lab--workshop/package.json` add it as a dependency:
    ```diff
   "dependencies": {
    +    "@bolt/components-button": "0.7.0-beta.5"
    }
    ```
1. Run `npm run bootstrap` at root of repo to symlink the new component up properly
1. Add component name to `.boltrc.js` in `apps/pattern-lab--workshop`.
1. Compile by running `npm run build` in `apps/pattern-lab--workshop`.

### List of components to update

- [x] `bolt-button` PR: #312
- [x] `bolt-background-shapes` PR: #316 
- [x] `bolt-background` PR: #320
- [x] `bolt-action-blocks`PR: #320
- [x] `bolt-blockquote` PR: #320
- [x] `bolt-button-group` PR: #320
- [x] `bolt-chip` PR: #320
- [x] `bolt-chip-list` PR: #320
- [x] `bolt-figure` PR: #320
- [x] `bolt-link` PR: #320
- [x] `bolt-ordered-list` PR: #320
- [x] `bolt-unordered-list` PR: #320
- [x] `bolt-teaser` PR: #320
- [x] `bolt-page-footer` PR: #320
- [x] `bolt-page-header` PR: #320
- [x] `bolt-site` PR: #320
- [x] `bolt-card` #343
- [x] `bolt-nav-bar` #346
- [x] `bolt-smooth-scroll` #346
- [x] `bolt-sticky` #346
- [x] `bolt-device-viewer` #346
- [x] `bolt-headline` #346
- [x] `bolt-image` - #345
- [x] `bolt-logo`- #345
- [x] `bolt-color-swatch` - belongs only in PL, appears to be done in eb7b0c7
- [x] ~`bolt-accordion`~ - removed in 5a4cd584
- [x] ~`bolt-critical-path`~ - removed in c60f1fabc
- [x] `bolt-icon`- #383
- [x] `bolt-icons`- #383
- **Items below here are available for anyone to start on**

- [ ] `bolt-band` - needs a single js entrypoint, which requires refactoring, possibly into two components...
- [ ] `bolt-critical-fonts` - the difference between `critical-fonts.scoped.scss` and critical-fonts.scss is unclear.  The javascript requires the scoped one; the package.json file has this line which looks like a mistake: `"style": "src/critical-fonts.css"`
- [ ] `bolt-quote` - not a Bolt package
- [ ] `bolt-video` - depends on brightcove-player
- [ ] `brightcove-player` - lots of extra complexity in package.json, Salem should probably handle this one

**Comment by EvanLovely** [comment]
Working on button; updated steps.

**Comment by EvanLovely** [comment]
Followed these instructions and updated the button; got a PR right here and it's nice and clean, so it should be a good guide: #312

**Comment by EvanLovely** [comment]
That PR got a bunch of other commits on it from changing around the base branch; basically it was just this commit, which gives a good idea of what the steps above produce: 60e314f6
